package webdriver.globalscripts.accessibilitytests;

public class DataMaintenanceAccessibilityDataAtoZPages {

  public static String[] expectedMaintainDataAtoZPagesCompleteListEchelon = {
//         "Activity Volume Data Scenarios",
          "Ad Hoc Statistic Masters",
          "Admission Sources",
          "Age In Days Groups",
//          "Age In Years Groups",
//          "AP DRG Fee Schedule Masters",
//          "AP DRG Groups",
//          "APC Fee Schedule Masters",
//          "APG Fee Schedule Masters",
//          "APR DRG Fee Schedule Masters",
//          "APR DRG Groups",
//          "ASC Schemes",
//          "Assigned Cost Destinations",
//          "Benefit Plan Groups",
//          "Benefit Plan Masters",
//          "Bill Types",
//          "Business Office Contacts",
//          "Care Delivery Networks",
//          "Care Delivery Settings",
//          "Charge Item Service Classification Schemes",
//          "Charge Masters",
//          "Chargeable Activity - HCPCS Code Mapping Schemes",
//          "Chargeable Activity - Revenue Code Mapping Schemes",
//          "Chargeable Activity Fee Schedule Masters",
//          "Chargeable Activity Groups",
//          "Commission Broker Agencies",
//          "Commission Brokers",
//          "Commission Types",
//          "Consumers",
//          "Contact Types",
//          "Contract Batches",
//          "Contract Types",
//          "Contractual Allowances",
//          "Cost Component Group Masters",
//          "Cost Component Masters",
//          "Cost Component Variability Masters",
//          "Cost Method Masters",
//          "Cost Model Scenario Results",
//          "Department Groups",
//          "Department Hierarchies",
//          "Department Masters",
//          "Discharge Statuses",
//          "DRG 1 Groups",
//          "DRG 2 Groups",
//          "DRG 3 Groups",
//          "DRG 4 Groups",
//          "EAPG Fee Schedule Masters",
//          "EAPG PAC Pricing Tables",
//          "EAPG Payment Action Codes",
//          "EFR Categories",
//          "Employer Group Types",
//          "Employer Groups",
//          "Employer Subgroup Types",
//          "Encounter Service Classification Schemes",
//          "Encounter Types",
//          "Encounters",
//          "Entities",
//          "Entity Groups",
//          "Entity Types",
//          "Ethnicities",
//          "Financial Categories",
//          "Genders",
//          "GL Account Hierarchies",
//          "GL Account Masters",
//          "GL Account Types",
//          "GL Adjustment and Reclassification Calculation Scenarios",
//          "GL Adjustment Masters",
//          "GL Data Scenarios",
//          "GL Reclassification Masters",
//          "GL Statistic Masters",
//          "Global Periods",
//          "GPCI Tables",
//          "Group Data Scenarios",
//          "Group Statistic Masters",
//          "HCFA DRG Fee Schedule Masters",
//          "HCFA DRG Groups",
//          "HCPCS Code Groups",
//          "HCPCS Code Masters",
//          "HCPCS Fee Schedule Masters",
//          "HCPCS Modifiers",
//          "Health Plan Representatives",
//          "ICD Diagnosis Groups",
//          "ICD Procedure Code Groups",
//          "ICD Procedure Code Masters",
//          "ICD Procedure Fee Schedule Masters",
//          "ICD10 Diagnosis Codes",
//          "ICD9 Diagnosis Codes",
//          "Industries",
//          "Industry Classification Schemes",
//          "Job Code Masters",  //added 4-20-20
//          "Jurisdictions",
//          "Labor Cost Components",  //added 4-20-20
//          "Labor RVU Calculation",  //added 4-20-20
//          "Level of Care Tables",
//          "Lines Of Business",
//          "Locations",
//          "Markets",
//          "Medical Service Assignments",
//          "Medicare Carriers",
//          "Medicare Entitlements",
//          "Medicare Localities",
//          "Medicare Plans",
//          "Medicare Renal Statuses",
//          "Medicare Types",
//          "Member Analysis Hierarchies",
//          "Member Designations",
//          "Member Statuses",
//          "Member Subgroup Aggregates",
//          "Membership Classification Schemes",
//          "Microcosting Wage Rates", //added 4-20-20
//          "Modifier Pricing Tables",
//          "MSDRG 1 Groups",
//          "MSDRG 2 Groups",
//          "MSDRG 3 Groups",
//          "MSDRG 4 Groups",
//          "MSDRG Fee Schedule Masters",
//          "Overhead Account Variability Masters",
//          "Overhead Model Scenario Results",
//          "Pay Type Masters",  //added 4-20-20
//          "Payment Organization Types",
//          "Payment Organizations",
//          "Places Of Service",
//          "Populations",
//          "Practitioner Groups",
//          "Practitioner Role Types",
//          "Practitioner Specialties",
//          "Practitioner Specialty Groups",
//          "Practitioners",
//          "Price List Calculation Scenarios",
//          "Price List to Encounters Assignments",
//          "Price Lists",
//          "Primary Care Specialties",
//          "Product Lines",
//          "Product Types",
//          "Psych Combined Comorbidity Assignments",
//          "RBRVS Conversion Factor Tables",
//          "RBRVS DRA Outpatient Cap Tables",
//          "RBRVS RVU Tables",
//          "Reimbursement Scenario Assignments",
//          "Relationships",
//          "Revenue Code Fee Schedule Masters",
//          "Revenue Code Groups",
//          "Revenue Code Major Categories",
//          "Revenue Code Masters",
//          "Riders",
//          "RVU Maintenance",
//          "Service Areas",
//          "Services",
//          "Site of Service Tables",
//          "Special Dependent Statuses",
//          "Staffing Data Scenarios", //added 4-20-20
//          "Statistic Data Scenarios",
//          "Status Indicators",
//          "Supply Code Masters",
//          "Time Periods",
//          "Transaction Classification Masters",
//          "Transaction Type Code Groups",
//          "Transaction Types",
//          "TRICARE DRG Fee Schedule Masters",
//          "TRICARE DRG Groups",
//          "Update Indicators",
//          "User Defined Fields And Relations",
//          "User Defined Industry Classification Scheme Types",
//          "User Defined Masters",
//          "User Defined Procedure Code Groups",
//          "User Defined Procedure Code Masters",
//          "Vendor Masters",
//          "Zip Code Groups",
  };

//  public static String[] expectedMaintainDataAtoZPagesCompleteListEvolve = {
//          "Activity Statistic Masters",
//          "Activity Volume Data Scenarios",
//          "Ad Hoc Statistic Masters",
//          "Admission Sources",
//          "Age In Days Groups",
//          "Age In Years Groups",
//          "AP DRG Fee Schedule Masters",
//          "AP DRG Groups",
//          "APC Fee Schedule Masters",
//          "APG Fee Schedule Masters",
//          "APR DRG Fee Schedule Masters",
//          "APR DRG Groups",
//          "ASC Schemes",
//          "Assigned Cost Destinations",
//          "Benefit Plan Groups",
//          "Benefit Plan Masters",
//          "Bill Types",
//          "Business Office Contacts",
//          "Care Delivery Networks",
//          "Care Delivery Settings",
//          "Charge Item Service Classification Schemes",
//          "Charge Masters",
//          "Chargeable Activity - HCPCS Code Mapping Schemes",
//          "Chargeable Activity - Revenue Code Mapping Schemes",
//          "Chargeable Activity Fee Schedule Masters",
//          "Chargeable Activity Groups",
//          "Commission Broker Agencies",
//          "Commission Brokers",
//          "Commission Types",
//          "Consumers",
//          "Contact Types",
//          "Contract Batches",
//          "Contract Types",
//          "Contractual Allowances",
//          "Cost Component Group Masters",
//          "Cost Component Masters",
//          "Cost Component Variability Masters",
//          "Cost Method Masters",
//          "Cost Model Scenario Results",
//          "Department Groups",
//          "Department Hierarchies",
//          "Department Masters",
//          "Discharge Statuses",
//          "DRG 1 Groups",
//          "DRG 2 Groups",
//          "DRG 3 Groups",
//          "DRG 4 Groups",
//          "EAPG Fee Schedule Masters",
//          "EAPG PAC Pricing Tables",
//          "EAPG Payment Action Codes",
//          "EFR Categories",
//          "Employer Group Types",
//          "Employer Groups",
//          "Employer Subgroup Types",
//          "Encounter Service Classification Schemes",
//          "Encounter Types",
//          "Encounters",
//          "Entities",
//          "Entity Groups",
//          "Entity Types",
//          "Ethnicities",
//          "Financial Categories",
//          "Genders",
//          "GL Account Hierarchies",
//          "GL Account Masters",
//          "GL Account Types",
//          "GL Adjustment and Reclassification Calculation Scenarios",
//          "GL Adjustment Masters",
//          "GL Data Scenarios",
//          "GL Reclassification Masters",
//          "GL Statistic Masters",
//          "Global Periods",
//          "GPCI Tables",
//          "Group Data Scenarios",
//          "Group Statistic Masters",
//          "HCFA DRG Fee Schedule Masters",
//          "HCFA DRG Groups",
//          "HCPCS Code Groups",
//          "HCPCS Code Masters",
//          "HCPCS Fee Schedule Masters",
//          "HCPCS Modifiers",
//          "Health Plan Representatives",
//          "ICD Diagnosis Groups",
//          "ICD Procedure Code Groups",
//          "ICD Procedure Code Masters",
//          "ICD Procedure Fee Schedule Masters",
//          "ICD10 Diagnosis Codes",
//          "ICD9 Diagnosis Codes",
//          "Industries",
//          "Industry Classification Schemes",
//          "Jurisdictions",
//          "Level of Care Tables",
//          "Lines Of Business",
//          "Locations",
//          "Markets",
//          "Medical Service Assignments",
//          "Medicare Carriers",
//          "Medicare Entitlements",
//          "Medicare Localities",
//          "Medicare Plans",
//          "Medicare Renal Statuses",
//          "Medicare Types",
//          "Member Analysis Hierarchies",
//          "Member Designations",
//          "Member Statuses",
//          "Member Subgroup Aggregates",
//          "Membership Classification Schemes",
//          "Modifier Pricing Tables",
//          "MSDRG 1 Groups",
//          "MSDRG 2 Groups",
//          "MSDRG 3 Groups",
//          "MSDRG 4 Groups",
//          "MSDRG Fee Schedule Masters",
//          "Overhead Account Variability Masters",
//          "Overhead Model Scenario Results",
//          "Payment Organization Types",
//          "Payment Organizations",
//          "Places Of Service",
//          "Populations",
//          "Practitioner Groups",
//          "Practitioner Role Types",
//          "Practitioner Specialties",
//          "Practitioner Specialty Groups",
//          "Practitioners",
//          "Price List Calculation Scenarios",
//          "Price List to Encounters Assignments",
//          "Price Lists",
//          "Primary Care Specialties",
//          "Product Lines",
//          "Product Types",
//          "Psych Combined Comorbidity Assignments",
//          "RBRVS Conversion Factor Tables",
//          "RBRVS DRA Outpatient Cap Tables",
//          "RBRVS RVU Tables",
//          "Reimbursement Scenario Assignments",
//          "Relationships",
//          "Revenue Code Fee Schedule Masters",
//          "Revenue Code Groups",
//          "Revenue Code Major Categories",
//          "Revenue Code Masters",
//          "Riders",
//          "RVU Maintenance",
//          "Service Areas",
//          "Services",
//          "Site of Service Tables",
//          "Special Dependent Statuses",
//          "Statistic Data Scenarios",
//          "Status Indicators",
//          "Supply Code Masters",
//          "Time Periods",
//          "Transaction Classification Masters",
//          "Transaction Type Code Groups",
//          "Transaction Types",
//          "TRICARE DRG Fee Schedule Masters",
//          "TRICARE DRG Groups",
//          "Update Indicators",
//          "User Defined Fields And Relations",
//          "User Defined Industry Classification Scheme Types",
//          "User Defined Masters",
//          "User Defined Procedure Code Groups",
//          "User Defined Procedure Code Masters",
//          "Vendor Masters",
//          "Zip Code Groups",
//  };
}
