# Properties for webdriver test framework

#testEnvironment can be qatest or evolve or echelon or appsupport (for accessibility testing)
# (default/commented out is qatest).
#testEnvironment = devstage
testEnvironment=qaapp
#browser can equal chrome, ie, firefox, or headless (for headless chrome). chrome is the default.
browser = chrome

#set printout (default/commented out=false) - this prints embedded comments when true
printout = true

# Path to drivers directory
drivers = C:/selenium/
