#Path to directory for output file
# Uncommenting line below prints only to console - select either this or section below (for console and file)
#appenders = console
# Uncomment both lines below when printing to console and file - be sure to set proper file path
#property.filename = C:\\Log4j2\\Axe Accessibility Reports
#property.filename = E:\\Shilpa\\AffinityDecisionSupport\\AffinityDecisionSupport - CIM\\Log4j2\\Axe Accessibility Reports
appenders = console, rolling

# console appender configuration
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %m%n

# rolling file appender configuration
appender.rolling.type = RollingFile
appender.rolling.name = AXELOG
appender.rolling.fileName = ${filename}/Axe Report.log
appender.rolling.filePattern = ${filename}/Axe Report.%d{MM-dd-yyyy}.log
#rolls log file per 1 day (since time.interval policy is 1)

#Configures the log line item format
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm} - %m%n

#configure rolling file policies
appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1
appender.rolling.policies.time.modulate = true
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 10

# loggers configuration (rolling file)
loggers = rolling
logger.rolling.name = Accessibility Report
logger.rolling.level = info
logger.rolling.appenderRefs = rolling
logger.rolling.appenderRef.rolling.ref = AXELOG

# root logger configuration (console)
rootLogger.level = info
## Select One: use lines below to print to console only - or use section below for printing to console and file
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT
## Select One: use lines below to print to console and file (then comment out 2 lines above)
#rootLogger.appenderRefs = stdout, rolling
#rootLogger.appenderRef.file.ref = AXELOG
#rootLogger.appenderRef.stdout.ref = STDOUT