TEST_ENVIRONMENT= devstage
#TEST_ENVIRONMENT= qastage
#VERSION=10.5.0-202205271701-R
VERSION=11.2.0-202305181956-R
BROWSER=chrome
#DRIVERS=C:/ADS_automation/AffinityDecisionSupport/src/selenium/
DRIVERS = ""
PRINTOUT=true
