#TEST_ENVIRONMENT= devstage
TEST_ENVIRONMENT= devstage
#VERSION=10.5.0-202205271701-R
VERSION=11.3.0-202507101422-R
BROWSER=chrome
#DRIVERS=C:/ADS_automation/AffinityDecisionSupport/src/selenium/
DRIVERS = ""
PRINTOUT=true
CALCTYPE="Activity Volume Calc Scenario: ADS-262 Vol Calc"
