#TEST_ENVIRONMENT= devstage
TEST_ENVIRONMENT= qastage
#VERSION=10.5.0-202205271701-R
VERSION=11.3.0-202507021320-R
BROWSER=edge
#DRIVERS=C:/ADS_automation/AffinityDecisionSupport/src/selenium/
DRIVERS = ""
PRINTOUT=true
CALCTYPE="Activity Volume Calc Scenario: ADS-262 Vol Calc"
