package webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({

	CorrectlySetValuesToNoneInSelectorsWhenPriorSelectionsChangedAds1216.class,
	CostModelScenarioSelectionAvailableAds1212.class,
	DepartmentSelectionAvailableAds1214.class,
	DisableApplySelectionsButtonIfAnyOfTheFiveRequiredFieldsAreSwitchedToNoneAds1217.class,
	HideSelectionsSoMoreVerticalRealEstateAds1211.class,
	ResultsStoredForSelectionAvailableAds1215.class,
	EntitySelectionAvailableAds1213.class,
	DepartmentSelectorEnabledWhenSpecificCmsSelectedAds1218.class,
	SelectColumnsPopupForColumnsToDisplayAds1083.class,
	UcqcColumnsToDisplaySectionAppearsAds1154.class,
	UcqcColumnsToDisplaySelectColumnsPopupAds1156.class,
	UcqcColumnsToDisplayStatusWithCostModelFieldChangesAds1156.class,
	//CostChangeColumnCheckNumberPlacesAndThousandsCommasAndDecimalPlacesAds1230.class,
	CostComponentColumnsDisplayTwoDecimalPlacesAds1185.class,
	UcqcApplySelectionsButtonActiveAndColumnHeadersDisplayAds1136.class,
	UcqcGridIsPopulatedAfterClickingApplySelectionsButtonAds1175.class,

})

public class UcqcMainPageSuite {
}
