package webdriver.suites.grouping;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import webdriver.globalscripts.help.HelpLinksContractingEditIppsUi2020Ads2525;
import webdriver.scripts.contracting.CalculateExistingPublishedContractAds1447;
import webdriver.scripts.contracting.ClearFilterbuttonModels;
import webdriver.scripts.contracting.ConfirmAddNewDeleteAPCFeeScheduleMasters;
import webdriver.scripts.contracting.ConfirmFY2023MedicareYearisAvailableForMedIPPS;
import webdriver.scripts.contracting.ContractingCostModelsSmokeTest;
import webdriver.scripts.contracting.ContractingModelDefinePaymentTermsFeeForServicePaymentTermsCalculate;
import webdriver.scripts.contracting.CopyPasteButtons;
import webdriver.scripts.contracting.CreateANewContractModel;
import webdriver.scripts.contracting.CreatingaNewContractingFolder;
import webdriver.scripts.contracting.EditRiskLimiterScreen;
import webdriver.scripts.contracting.EntityLevelSecurityContracting;
import webdriver.scripts.contracting.FilterbuttonModels;
import webdriver.scripts.contracting.GeneralContractInfo;
import webdriver.scripts.contracting.ModelContractLumpSumPaymentAllocation;
import webdriver.scripts.contracting.ModelContractPatientFinancialResponsibility;
import webdriver.scripts.contracting.NewContractType;
import webdriver.scripts.contracting.UIValidationContracting;
import webdriver.scripts.contracting.UIValidationPrepareTables;
import webdriver.scripts.contracting.ValidateBenefitPlanInfoUpdate;
import webdriver.scripts.contracting.ValidateBenifitPlansInfoForMultipleUnpublishedContracts;
import webdriver.scripts.contracting.ValidateContractingModeExportImportButton;
import webdriver.scripts.contracting.VerifyFilterAscSchemes;


@RunWith(Suite.class)
@Suite.SuiteClasses({
	HelpLinksContractingEditIppsUi2020Ads2525.class,
	CalculateExistingPublishedContractAds1447.class,
	ClearFilterbuttonModels.class,
	ConfirmAddNewDeleteAPCFeeScheduleMasters.class,
	ConfirmFY2023MedicareYearisAvailableForMedIPPS.class,
	ContractingCostModelsSmokeTest.class,
	ContractingModelDefinePaymentTermsFeeForServicePaymentTermsCalculate.class,
	CopyPasteButtons.class,
	CreateANewContractModel.class,
	CreatingaNewContractingFolder.class,
	EditRiskLimiterScreen.class,
	EntityLevelSecurityContracting.class,
	FilterbuttonModels.class,
	GeneralContractInfo.class,
	ModelContractLumpSumPaymentAllocation.class,
	ModelContractPatientFinancialResponsibility.class,
	NewContractType.class,
	UIValidationContracting.class,
	UIValidationPrepareTables.class,
	ValidateBenefitPlanInfoUpdate.class,
	ValidateBenifitPlansInfoForMultipleUnpublishedContracts.class,
	ValidateContractingModeExportImportButton.class,
	VerifyFilterAscSchemes.class,

})
public class ContractModels {

}
