package webdriver.suites.grouping;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import webdriver.globalscripts.help.HelpLinksDataMaintenancePageAds2526;
import webdriver.scripts.contracting.ContractingDataMaintenanceNewItem;
import webdriver.scripts.contracting.GeneratePsychCombinedComorbidityFactor;
import webdriver.scripts.contracting.ValidateContracDataMaintenanceBubble;
import webdriver.scripts.contracting.ValidateContractingTreeTab;
import webdriver.scripts.costing.ValidateHelpLinkHideTabDataMaintenance;
import webdriver.scripts.datamaintenance.maintaindata.CreateDeleteCostMethodDeptMasterDischargeStatus;
import webdriver.scripts.datamaintenance.maintaindata.CreateEditDeleteNewStructurePopulations;
import webdriver.scripts.datamaintenance.maintaindata.DataMaintenanceAtoZTabPageLoads;
import webdriver.scripts.datamaintenance.maintaindata.DataMaintenanceTreePageLoads;
import webdriver.scripts.datamaintenance.maintaindata.RunEncounterServiceClassificationScheme;
import webdriver.scripts.regression.generalcalculations.GeneralCalculationsChargeItemServiceClassificationSchemeAds2342;
import webdriver.scripts.regression.generalcalculations.GeneralCalculationsEncounterServiceClassificationSchemeAds2341;
import webdriver.scripts.regression.generalcalculations.GeneralCalculationsRunContractualAllowancesScenarioAds2163;
import webdriver.scripts.regression.generalcalculations.GeneralCalculationsRunMedicalServiceAssignmentAds2343;
import webdriver.scripts.regression.generalcalculations.GeneralCalculationsRunPriceListCalculationScenarioAds2274;
import webdriver.scripts.regression.generalcalculations.GeneralCalculationsRunPriceListEncounterAssignmentAds2344;
import webdriver.scripts.systemmaintenance.DepartmentLevelSecurity;
@RunWith(Suite.class)
@Suite.SuiteClasses({
	ValidateHelpLinkHideTabDataMaintenance.class,
	HelpLinksDataMaintenancePageAds2526.class,
	ContractingDataMaintenanceNewItem.class,
	GeneratePsychCombinedComorbidityFactor.class,
	ValidateContracDataMaintenanceBubble.class,
	ValidateContractingTreeTab.class,
	DataMaintenanceAtoZTabPageLoads.class,
	DataMaintenanceTreePageLoads.class,
	RunEncounterServiceClassificationScheme.class,
	CreateEditDeleteNewStructurePopulations.class,
	CreateDeleteCostMethodDeptMasterDischargeStatus.class,
	GeneralCalculationsEncounterServiceClassificationSchemeAds2341.class,
	GeneralCalculationsChargeItemServiceClassificationSchemeAds2342.class,
	GeneralCalculationsRunContractualAllowancesScenarioAds2163.class,
	GeneralCalculationsRunMedicalServiceAssignmentAds2343.class,
	GeneralCalculationsRunPriceListCalculationScenarioAds2274.class,
	GeneralCalculationsRunPriceListEncounterAssignmentAds2344.class,
	DepartmentLevelSecurity.class,

})
public class MaintainData {

}
