package webdriver.suites.grouping;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import webdriver.globalscripts.help.UcqcSelectColumnsDialogVerifyOnlineHelpAds1113;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.CostChangeColumnsPopulateAfterCalculateAds1230;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.LoadingSpinnerDisplaysWhileCalculationIsRunningAds1231;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.QuickCcCostColumnsForEachCostComponentPopulateAfterCalculateAds1229;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.RunCalculationAndAssertTotalChangeColumnCalculatesProperlyAds1278;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.TotalQuickCostColumnPopulatesAfterCalculateDatabaseChecks;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.TotalQuickCostColumnPopulatesAfterCalculateStaticAds1228;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.UcqcCalculateButtonDisabledIfAttemptToCalculateWithUnsavedQuickRvusAds1233;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.UcqcCalculateButtonEnableAndDisableAds1152;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.UcqcCalculateUcqcWithPublishedCmsAds1384;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.UcqcCalculateUcqcWithSixDigitQuickRvusAds1377;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.UcqcCalculationFailsWhenDeptSelectedNoLongerExistsInSelectedCms;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.UcqcCreateCopyOfCmsToStoreResultsOfUcqcCalculationCmsScenarioAds1378;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.UpdateUCQCParmsRvuCalcScenario;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.ValidateTotalChangeValueCalculationStaticAds1278;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.VerifyUCQCButtonsBackgroundColor;
import webdriver.scripts.costing.unitcostquickcalculation.ucqccalculation.VerifyUCQCdropdownValuesForOptionNone;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.CorrectlySetValuesToNoneInSelectorsWhenPriorSelectionsChangedAds1216;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.CostChangeColumnCheckNumberPlacesAndThousandsCommasAndDecimalPlacesAds1230;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.CostComponentColumnsDisplayTwoDecimalPlacesAds1185;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.CostModelScenarioSelectionAvailableAds1212;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.DepartmentSelectionAvailableAds1214;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.DepartmentSelectorEnabledWhenSpecificCmsSelectedAds1218;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.DisableApplySelectionsButtonIfAnyOfTheFiveRequiredFieldsAreSwitchedToNoneAds1217;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.EntitySelectionAvailableAds1213;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.HideSelectionsSoMoreVerticalRealEstateAds1211;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.ResultsStoredForSelectionAvailableAds1215;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.SelectColumnsPopupForColumnsToDisplayAds1083;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.UcqcApplySelectionsButtonActiveAndColumnHeadersDisplayAds1136;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.UcqcColumnsToDisplaySectionAppearsAds1154;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.UcqcColumnsToDisplaySelectColumnsPopupAds1156;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.UcqcColumnsToDisplayStatusWithCostModelFieldChangesAds1156;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.UcqcGridIsPopulatedAfterClickingApplySelectionsButtonAds1175;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcmainpage.UcqcIncludeInGridOnlyChargeCodesWithResultsInSelectedCmsAds1115;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.OverWriteRVUValues5919;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.OverwriteRvuMaintenancePopupAds1181;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.UcqcCopyToQuickRvusPopupIsLaunchedAds1148;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.UcqcEnableDisableOverwriteRvuMaintenanceButtonAds1182;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.UcqcEnablingAndDisablingClearQuickRvusAndSaveButtonAds1138;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.UcqcEnablingAndDisablingCopyToQuickRvusButtonAds1137;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.UcqcSourceCostComponentLabelDisplaysCorrectlyOnCopyToQuickRvusPopupAds1178;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.UcqcUndoAndSaveQuickRvusAds1151;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.UcqcWarningPopsUpWhenClearQuickRvusAndSaveButtonIsClickedAds1142;
import webdriver.scripts.costing.unitcostquickcalculation.ucqcrvus.ValidateWarningForRvuMaintenancePopUpAds1249;
import webdriver.scripts.security.ucqcroles.CostMgrXCostAnalystBubbleNavigationStaticAds1466;
import webdriver.scripts.security.ucqcroles.UcqcLinkInCostingBubbleDisplayedAds1466;
import webdriver.scripts.security.ucqcroles.UcqcLinkInCostingBubbleNotDisplayedStaticAds1466;

@RunWith(Suite.class)
@Suite.SuiteClasses({
	CorrectlySetValuesToNoneInSelectorsWhenPriorSelectionsChangedAds1216.class,
	CostChangeColumnCheckNumberPlacesAndThousandsCommasAndDecimalPlacesAds1230.class,
	CostComponentColumnsDisplayTwoDecimalPlacesAds1185.class,
	CostModelScenarioSelectionAvailableAds1212.class,
	DepartmentSelectionAvailableAds1214.class,
	DepartmentSelectorEnabledWhenSpecificCmsSelectedAds1218.class,
	DisableApplySelectionsButtonIfAnyOfTheFiveRequiredFieldsAreSwitchedToNoneAds1217.class,
	EntitySelectionAvailableAds1213.class,
	HideSelectionsSoMoreVerticalRealEstateAds1211.class,
	ResultsStoredForSelectionAvailableAds1215.class,
	SelectColumnsPopupForColumnsToDisplayAds1083.class,
	UcqcApplySelectionsButtonActiveAndColumnHeadersDisplayAds1136.class,
	UcqcColumnsToDisplaySectionAppearsAds1154.class,
	UcqcColumnsToDisplaySelectColumnsPopupAds1156.class,
	UcqcColumnsToDisplayStatusWithCostModelFieldChangesAds1156.class,
	UcqcGridIsPopulatedAfterClickingApplySelectionsButtonAds1175.class,
	UcqcIncludeInGridOnlyChargeCodesWithResultsInSelectedCmsAds1115.class,
	OverwriteRvuMaintenancePopupAds1181.class,
	UcqcCopyToQuickRvusPopupIsLaunchedAds1148.class,
	UcqcEnableDisableOverwriteRvuMaintenanceButtonAds1182.class,
	UcqcEnablingAndDisablingClearQuickRvusAndSaveButtonAds1138.class,
	UcqcEnablingAndDisablingCopyToQuickRvusButtonAds1137.class,
	UcqcSourceCostComponentLabelDisplaysCorrectlyOnCopyToQuickRvusPopupAds1178.class,
	UcqcUndoAndSaveQuickRvusAds1151.class,
	UcqcWarningPopsUpWhenClearQuickRvusAndSaveButtonIsClickedAds1142.class,
	ValidateWarningForRvuMaintenancePopUpAds1249.class,
	OverWriteRVUValues5919.class,
	UcqcLinkInCostingBubbleDisplayedAds1466.class,
	CostMgrXCostAnalystBubbleNavigationStaticAds1466.class,
	UcqcLinkInCostingBubbleNotDisplayedStaticAds1466.class,
	UcqcCopyToQuickRvusPopupIsLaunchedAds1148.class,
	UcqcSelectColumnsDialogVerifyOnlineHelpAds1113.class,
	CostChangeColumnsPopulateAfterCalculateAds1230.class,
	LoadingSpinnerDisplaysWhileCalculationIsRunningAds1231.class,
	QuickCcCostColumnsForEachCostComponentPopulateAfterCalculateAds1229.class,
	RunCalculationAndAssertTotalChangeColumnCalculatesProperlyAds1278.class,
	TotalQuickCostColumnPopulatesAfterCalculateDatabaseChecks.class,
	TotalQuickCostColumnPopulatesAfterCalculateStaticAds1228.class,
	UcqcCalculateButtonDisabledIfAttemptToCalculateWithUnsavedQuickRvusAds1233.class,
	UcqcCalculateButtonEnableAndDisableAds1152.class,
	UcqcCalculateUcqcWithPublishedCmsAds1384.class,
	UcqcCalculateUcqcWithSixDigitQuickRvusAds1377.class,
	UcqcCalculationFailsWhenDeptSelectedNoLongerExistsInSelectedCms.class,
	UcqcCreateCopyOfCmsToStoreResultsOfUcqcCalculationCmsScenarioAds1378.class,
	ValidateTotalChangeValueCalculationStaticAds1278.class,
	VerifyUCQCButtonsBackgroundColor.class,
	VerifyUCQCdropdownValuesForOptionNone.class,
	UpdateUCQCParmsRvuCalcScenario.class,
})
public class UnitCostQuickCalculation {
		
}
