package webdriver.scripts.datamaintenance.az;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({
//	ActivityStatisticMasters.class,
//	ActivityVoulmeDataScenarios.class,
//	AdmissionSources.class,
//	AgeInYearsGroups.class,
//	APCFeeScheduleMasters.class,
//	APDRGFeeScheduleMasters.class,
//	ApDrgGroups.class,
//	APGFeeScheduleMasters.class,
//	APRDRGFeeScheduleMasters.class,
//	AprDrgGroups.class,
//	ASCSchemes.class,
//	BenefitPlanGroup.class,
//	BenefitPlanMasters.class,
//	BusinessOfficeContacts.class,
//	CareDeliveryNetworks.class,
//	CareDeliverySettings.class,
//	ChargeableActivityFeeScheduleMasters.class,
//	ChargeableActivityGroup.class,
//	ChargeableActivityHCPCSCodeMappingSchemes.class,
//	ChargeableActivityRevenueCodeMappingSchemes.class,
//	ChargeItemServiceClassificationSchemes.class,
//	CommissionBrokerAgencies.class,
//	CommissionBrokers.class,
//	CommissionTypes.class,
//	Consumers.class,
//	ContactTypes.class,
//	ContractBatches.class,
//	ContractTypes.class,
//	ContractualAllowances.class,
//	CostComponentGroupMasters.class,
//	CostComponentMasters.class,
//	CostComponentVariabilityMasters.class,
//	CostMethodMasters.class,
//	DepartmentGroup.class,
//	DischargeStatuses.class,
//	DRG1Groups.class,
//	DRG2Groups.class,
//	DRG3Groups.class,
//	DRG4Groups.class,
//	EAPGFeeScheduleMasters.class,
//	EAPGPaymentActionCodes.class,
//	EditConsumerHistoryRecord.class,
//	EFRCategories.class,
//	EntityTypes.class,
//	Ethnicities.class,
//	Genders.class,
//	GlobalPeriods.class,
//	HCFADRGFeeScheduleMasters.class,
//	HCFADRGGroups.class,
//	HCPCSCodeGroups.class,
//	HCPCSFeeScheduleMasters.class,
//	HCPCSModifiers.class,
//	ICD10DiagnosisCodes.class,
//	ICD9DiagnosisCodes.class,
//	ICDProcedureCodeGroups.class,
//	ICDProcedureFeeScheduleMasters.class,
//	JobCodeGroups.class,
//	JobCodeMasters.class,
//	LinesOfBusiness.class,
//	Locations.class,
//	MedicareCarriers.class,
//	MedicareEntitlements.class,
//	MedicarePlans.class,
//	MedicareRenalStatuses.class,
//	MedicareTypes.class,
//	MemberStatuses.class,
//	MSDRG1Groups.class,
//	MSDRG2Groups.class,
//	MSDRG3Groups.class,
//	MSDRG4Groups.class,
//	MSDRGFeeScheduleMasters.class,
//	PaymentOrganizationTypes.class,
//	PayTypeGroups.class,
//	PlacesOfService.class,
//	PractitionerGroups.class,
//	PractitionerRoleTypes.class,
//	PractitionerSpecialties.class,
//	PractitionerSpecialtyGroups.class,
//	PrimaryCareSpecialties.class,
//	ProductLines.class,
//	ProductTypes.class,
//	Relationships.class,
//	RevenueCodeFeeScheduleMasters.class,
//	RevenueCodeGroups.class,
//	RevenueCodeMajorCategories.class,
//	Riders.class,
//	ServiceAreas.class,
//	StatusDependentStatuses.class,
//	StatusIndicators.class,
//	SupplyCodeMasters.class,
//	TransactionClassificationMasters.class,
//	TransactionTypeCodeGroups.class,
//	TransactionTypes.class,
//	TRICAREDRGGroups.class,
//	UpdateIndicators.class,
//	UserDefinedIndustryClassificationSchemeTypes.class,
//	UserDefinedMasters.class,
//	UserDefinedProcedureCodeGroups.class,
//	UserDefinedProcedureCodeMasters.class,
//	VendorMasters.class,

	
	
	
})




public class MaintaindataTestSuite {

}
